import {choose, navigate} from './helpers';
import {test, expect} from '@playwright/test';

const localTime = offset => {
  const date = new Date(Date.now()+offset);
  return new Date(date-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
};

test('create, submit, judge, publish and export an event through the browser', async ({page}) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const eventName = `Lifecycle ${Date.now()}`;
  const section = name => page.locator('section:visible').filter({has:page.getByRole('heading',{name,exact:true})});
  const signIn = async role => {
    await page.getByRole('button',{name:'Sign out'}).click();
    await page.getByRole('button',{name:role,exact:true}).click();
  };
  await page.goto('/');
  await page.getByRole('button',{name:'Organizer',exact:true}).click();
  await navigate(page, 'Settings');
  const create = section('Create an event');
  await create.getByPlaceholder('Event name',{exact:true}).fill(eventName);
  await create.getByLabel('Starts',{exact:true}).fill(localTime(-3600000));
  await create.getByLabel('Submissions close',{exact:true}).fill(localTime(3600000));
  await create.getByPlaceholder('Tracks, comma separated').fill('Open innovation');
  await create.getByPlaceholder('Prizes, comma separated').fill('Best working product');
  await create.getByRole('button',{name:'Create event',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Select event',exact:true})).toHaveText(eventName);
  await expect(page.getByRole('combobox',{name:'Select event',exact:true})).toBeEnabled();
  const eventId = await page.getByRole('combobox',{name:'Select event',exact:true}).getAttribute('data-value');
  await navigate(page, 'Judging');
  await page.getByPlaceholder('Registered email').fill('marek.nowak@example.org');
  await page.getByRole('button',{name:'Add role',exact:true}).click();
  await navigate(page, 'Judging');
  await expect(section('Judging progress').getByText('Marek Nowak',{exact:true})).toBeVisible();
  await signIn('Participant');
  await choose(page, 'Select event', eventId);
  await page.getByPlaceholder('Team name',{exact:true}).fill('Lifecycle builders');
  await page.getByRole('button',{name:'Create team',exact:true}).click();
  await page.getByPlaceholder('Project title',{exact:true}).fill('A complete lifecycle');
  await page.getByPlaceholder('Short summary',{exact:true}).fill('A working event from registration through published results.');
  await page.getByPlaceholder('Full project story: the problem, approach and what you built').fill('Built and reviewed using the real shared portal.');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.getByRole('button',{name:'Submit project',exact:true}).click();
  await expect(page.getByRole('button',{name:'Submit project',exact:true})).toHaveCount(0);
  expect((await page.request.get(`/dogfood-api/events/${eventId}/results`)).status()).toBe(403);
  await signIn('Organizer');
  await choose(page, 'Select event', eventId);
  await navigate(page, 'Judging');
  await page.getByLabel('Reviews per project',{exact:true}).fill('1');
  await page.getByRole('button',{name:'Assign batch',exact:true}).click();
  await expect(page.getByText('1 new assignments.',{exact:true})).toBeVisible();
  await signIn('Participant');
  await choose(page, 'Select event', eventId);
  await expect(page.getByLabel('Project track',{exact:true})).toBeDisabled();
  await expect(page.getByText('The track is fixed because judges have been assigned.',{exact:false})).toBeVisible();
  await page.getByPlaceholder('Short summary',{exact:true}).fill('Updated after assignment, before the deadline.');
  const savedProject = page.waitForResponse(response => response.request().method() === 'PATCH' && response.url().includes('/dogfood-api/projects/'));
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  expect((await savedProject).status()).toBe(200);
  await signIn('Judge');
  await choose(page, 'Select event', eventId);
  const review = section('Assigned reviews');
  await review.getByLabel('Functionality · weight 1',{exact:true}).fill('5');
  await review.getByLabel('Quality · weight 1',{exact:true}).fill('4');
  await review.getByLabel('Innovation · weight 1',{exact:true}).fill('3');
  await review.getByPlaceholder('Review notes').fill('Complete and usable end to end.');
  await review.getByRole('button',{name:'Submit review',exact:true}).click();
  await expect(review.getByRole('button',{name:'Update review',exact:true})).toBeVisible();
  await signIn('Organizer');
  await choose(page, 'Select event', eventId);
  await navigate(page, 'Judging');
  await expect(section('Judging progress').getByText('1/1',{exact:true})).toBeVisible();
  await navigate(page, 'Settings');
  await section('Event controls').getByLabel('Submissions close',{exact:true}).fill(localTime(-60000));
  await section('Event controls').getByRole('button',{name:'Save settings',exact:true}).click();
  await navigate(page, 'Results');
  await page.getByRole('button',{name:'Publish results',exact:true}).click();
  await expect(page.getByText('Published snapshot',{exact:true})).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link',{name:'Export CSV',exact:true}).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('dogfood-results.csv');
  const stream = await download.createReadStream();
  let csv = ''; for await (const chunk of stream) csv += chunk.toString();
  expect(csv).toContain('A complete lifecycle');
  expect(csv).toContain('judge-mean-shrinkage-v1');
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.goto(`/events/${eventId}/projects`);
  await expect(page.getByRole('heading',{name:'Published judging results'})).toBeVisible();
  await expect(page.getByRole('row').filter({hasText:'A complete lifecycle'})).toContainText('4.000');
  await page.screenshot({path:'test-results/lifecycle-public-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/lifecycle-public-mobile.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
